### ISSUE TITLE
Flashed xPRO V5 Only communicating with X axis driver

### ISSUE THREAD

**Issue by BluePaci** [grblHAL/ESP32#100]
Hi, i've flashed the webbuild xPRO V5 firmware onto verified to be working hardware and only the X axis motors receive step pulses and power. Unsure of what the root cause is. happy to try potential solutions on my own hardware. I've checked that the pin map is correct and consistent with my existing fluidNC install, as well as config settings. (Going back to FluidNC fixes the issue)

**Comment by terjeio** [comment]
$338 is set to 7 to enable all Trinamic drivers?
What is the output from M122? M122I?
