### ISSUE TITLE
unable to compile latest version

### ISSUE THREAD

**Issue by boboxx** [grblHAL/ESP32#113]
Processing esp32 (platform: espressif32 @ ~4.0.0; framework: espidf; board: esp32dev)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (4.0.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf @ 3.40302.0 (4.3.2) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.30100.210531 (3.1.0) 
 - tool-ninja @ 1.9.0 
 - toolchain-esp32ulp @ 1.22851.191205 (2.28.51) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2
Reading CMake configuration...
Generating assembly for certificate bundle...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ off
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Generating assembly for .pio/build/esp32/favicon.ico.S
Generating assembly for .pio/build/esp32/ap_login.html.S
Generating assembly for .pio/build/esp32/index.html.gz.S
Compiling .pio/build/esp32/main/main.o
Compiling .pio/build/esp32/main/driver.o
Compiling .pio/build/esp32/main/nvs.o
Compiling .pio/build/esp32/main/uart_serial.o
Compiling .pio/build/esp32/main/ioports.o
Compiling .pio/build/esp32/main/ioports_analog.o
Compiling .pio/build/esp32/main/i2c.o
Compiling .pio/build/esp32/main/ioexpand.o
Compiling .pio/build/esp32/main/boards/BlackBoxX32.o
Compiling .pio/build/esp32/main/networking/strutils.o
Compiling .pio/build/esp32/main/grbl/grbllib.o
Compiling .pio/build/esp32/main/grbl/coolant_control.o
Compiling .pio/build/esp32/main/grbl/crossbar.o
Compiling .pio/build/esp32/main/grbl/nvs_buffer.o
Compiling .pio/build/esp32/main/grbl/gcode.o
Compiling .pio/build/esp32/main/grbl/machine_limits.o
Compiling .pio/build/esp32/main/grbl/messages.o
Compiling .pio/build/esp32/main/grbl/modbus.o
Compiling .pio/build/esp32/main/grbl/motion_control.o
Compiling .pio/build/esp32/main/grbl/nuts_bolts.o
Compiling .pio/build/esp32/main/grbl/override.o
Compiling .pio/build/esp32/main/grbl/planner.o
Compiling .pio/build/esp32/main/grbl/protocol.o
Compiling .pio/build/esp32/main/grbl/report.o
Compiling .pio/build/esp32/main/grbl/settings.o
Compiling .pio/build/esp32/main/grbl/sleep.o
Compiling .pio/build/esp32/main/grbl/spindle_control.o
Compiling .pio/build/esp32/main/grbl/state_machine.o
Compiling .pio/build/esp32/main/grbl/stream.o
Compiling .pio/build/esp32/main/grbl/stepper.o
Compiling .pio/build/esp32/main/grbl/stepper2.o
Compiling .pio/build/esp32/main/grbl/system.o
Compiling .pio/build/esp32/main/grbl/tool_change.o
Compiling .pio/build/esp32/main/grbl/alarms.o
Compiling .pio/build/esp32/main/grbl/errors.o
Compiling .pio/build/esp32/main/grbl/ngc_expr.o
Compiling .pio/build/esp32/main/grbl/ngc_params.o
Compiling .pio/build/esp32/main/grbl/ngc_flowctrl.o
Compiling .pio/build/esp32/main/grbl/regex.o
Compiling .pio/build/esp32/main/grbl/ioports.o
Compiling .pio/build/esp32/main/grbl/vfs.o
Compiling .pio/build/esp32/main/grbl/kinematics/corexy.o
Compiling .pio/build/esp32/main/grbl/kinematics/wall_plotter.o
Compiling .pio/build/esp32/main/grbl/kinematics/delta.o
Compiling .pio/build/esp32/main/grbl/kinematics/polar.o
Compiling .pio/build/esp32/main/littlefs_hal.o
Compiling .pio/build/esp32/main/littlefs/lfs.o
Compiling .pio/build/esp32/main/littlefs/lfs_util.o
Compiling .pio/build/esp32/main/sdcard/fs_littlefs.o
Compiling .pio/build/esp32/main/i2s_out.o
Compiling .pio/build/esp32/main/grbl/my_plugin.o
Compiling .pio/build/esp32/main/wifi.o
Compiling .pio/build/esp32/main/mqtt.o
Compiling .pio/build/esp32/main/dns_server.o
Compiling .pio/build/esp32/main/networking/httpd.o
Compiling .pio/build/esp32/main/networking/http_upload.o
Compiling .pio/build/esp32/main/networking/telnetd.o
Compiling .pio/build/esp32/main/networking/websocketd.o
Compiling .pio/build/esp32/main/networking/base64.o
Compiling .pio/build/esp32/main/networking/sha1.o
Compiling .pio/build/esp32/main/networking/urlencode.o
Compiling .pio/build/esp32/main/networking/urldecode.o
Compiling .pio/build/esp32/main/networking/utils.o
Compiling .pio/build/esp32/main/networking/multipartparser.o
Compiling .pio/build/esp32/main/networking/networking.o
Compiling .pio/build/esp32/main/networking/fs_ram.o
Compiling .pio/build/esp32/main/networking/fs_stream.o
Compiling .pio/build/esp32/main/networking/webdav.o
Compiling .pio/build/esp32/main/networking/ssdp.o
Compiling .pio/build/esp32/main/networking/ftpd.o
Compiling .pio/build/esp32/main/networking/sfifo.o
Compiling .pio/build/esp32/main/keypad/keypad.o
Compiling .pio/build/esp32/main/keypad/macros.o
Compiling .pio/build/esp32/main/spi.o
Compiling .pio/build/esp32/main/trinamic_if.o
Compiling .pio/build/esp32/main/motors/trinamic.o
Compiling .pio/build/esp32/main/trinamic/common.o
Compiling .pio/build/esp32/main/trinamic/tmc_interface.o
Compiling .pio/build/esp32/main/trinamic/tmc2130.o
Compiling .pio/build/esp32/main/trinamic/tmc2130hal.o
Compiling .pio/build/esp32/main/trinamic/tmc2209.o
main/spi.c: In function 'spi_put_byte':
main/spi.c:135:39: error: 'SPI_TRANS_MODE_OCT' undeclared (first use in this function); did you mean 'SPI_TRANS_MODE_QIO'?
         .flags = SPI_TRANS_USE_TXDATA|SPI_TRANS_MODE_OCT,
                                       ^~~~~~~~~~~~~~~~~~
                                       SPI_TRANS_MODE_QIO
main/spi.c:135:39: note: each undeclared identifier is reported only once for each function it appears in
Compiling .pio/build/esp32/main/trinamic/tmc2209hal.o
*** [.pio/build/esp32/main/spi.o] Error 1
========================= [FAILED] Took 12.11 seconds =========================

**Comment by terjeio** [comment]
Remove SPI_TRANS_MODE_OCT and see what happens. I added this a few days ago so must be another incompatible Espressif change in the frameworks of theirs... (I am using IDF 4.4.3).

**Comment by boboxx** [comment]
[ESP32](https://github.com/grblHAL/ESP32/tree/master)
/platformio.ini

Should be updated to include:
platform = espressif32 @ ~5.0.0

**Comment by boboxx** [comment]
I just tried the web buildwer and it's also failling wit the same problem :)

Command failed: pio run -etest -cjob.ini

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
main/spi.c: In function 'spi_put_byte':
main/spi.c:135:39: error: 'SPI_TRANS_MODE_OCT' undeclared (first use in this function); did you mean 'SPI_TRANS_MODE_QIO'?
.flags = SPI_TRANS_USE_TXDATA|SPI_TRANS_MODE_OCT,
^~~~~~~~~~~~~~~~~~
SPI_TRANS_MODE_QIO
main/spi.c:135:39: note: each undeclared identifier is reported only once for each function it appears in
*** [.pio/build/test/main/spi.o] Error 1
========================= [FAILED] Took 27.62 seconds =========================
