### ISSUE TITLE
Primary UART - hard coded

### ISSUE THREAD

**Issue by boboxx** [grblHAL/ESP32#125]
Is there a reason Primary UART is hard coded to pin 34 and 35 on the ESP32 and not configurable like the rest of the pins?

**Comment by terjeio** [comment]
No, if needed overridable symbols for the pin numbers could be added.

**Comment by boboxx** [comment]
It's ok, I simply edited uart_serial.c. I just wanted to make sure I had not missed anything. Pin35 is my Y limit sensor as it's inline with the rest of the limit switch.
