### ISSUE TITLE
$pins reporting

### ISSUE THREAD

**Issue by boboxx** [grblHAL/ESP32#130]
Looks like there is issue with pins reporting. most are all I2S now!

latest pull:
[PIN:I2S34,Feed hold]
[PIN:I2S36,Cycle start]
[PIN:I2S39,Probe]
[PIN:I2S33,X limit min]
[PIN:I2S32,Y limit min]
[PIN:I2S12,Y limit min 2]
[PIN:I2S22,Z limit min]
[PIN:I2S12,Aux in 0,P0]
[PIN:I2S1,X step]
[PIN:I2S4,Y step]
[PIN:I2S10,Y2 step]
[PIN:I2S7,Z step]
[PIN:I2S2,X dir]
[PIN:I2S5,Y dir]
[PIN:I2S11,Y2 dir]
[PIN:I2S8,Z dir]
[PIN:I2S0,X enable]
[PIN:I2S3,Y enable]
[PIN:I2S9,Y enable]
[PIN:I2S6,Z enable]
[PIN:I2S17,Spindle on]
[PIN:I2S18,Spindle direction]
[PIN:2,Spindle PWM]
[PIN:I2S20,Mist]
[PIN:I2S19,Flood]
[PIN:I2S19,MISO]
[PIN:I2S23,MOSI]
[PIN:I2S18,SPI CLK]
[PIN:5,SD card CS]
[PIN:I2S34,RX,Primary UART]
[PIN:I2S35,TX,Primary UART]
[PIN:I2S16,RX,Modbus]
[PIN:I2S17,TX,Modbus]

Old version:
[PIN:34,Feed hold]
[PIN:36,Cycle start]
[PIN:39,Probe]
[PIN:33,X limit min]
[PIN:32,Y limit min]
[PIN:35,Y limit min 2]
[PIN:22,Z limit min]
[PIN:12,Aux in 0,P0]
[PIN:I2S1,X step]
[PIN:I2S4,Y step]
[PIN:I2S10,Y2 step]
[PIN:I2S7,Z step]
[PIN:I2S2,X dir]
[PIN:I2S5,Y dir]
[PIN:I2S11,Y2 dir]
[PIN:I2S8,Z dir]
[PIN:I2S0,X enable]
[PIN:I2S3,Y enable]
[PIN:I2S9,Y enable]
[PIN:I2S6,Z enable]
[PIN:I2S17,Spindle on]
[PIN:I2S18,Spindle direction]
[PIN:2,Spindle PWM]
[PIN:I2S20,Mist]
[PIN:I2S19,Flood]
[PIN:19,MISO]
[PIN:23,MOSI]
[PIN:18,SPI CLK]
[PIN:5,SD card CS]
[PIN:13,RX,Primary UART]
[PIN:4,TX,Primary UART]
[PIN:16,RX,Modbus]
[PIN:17,TX,Modbus]

**Comment by terjeio** [comment]
The latest changes revealed an old bug, fixed now.
