### ISSUE TITLE
Problem with ESP-WROOOM-32

### ISSUE THREAD

**Issue by vvv1954** [grblHAL/ESP32#22]
Hello,

I compiled codes with basic functions (no WiFi, no SD, etc) and uploaded the firmware to ESP-WROOOM-32.  But when connected it goes to the loop sending the welcome message. 
![image](https://user-images.githubusercontent.com/77076378/162591363-d7702e7c-0f29-4a61-97ea-ccbb025e1ba0.png)
Also I tried one of yours build (Fix for issue #21) - the same problem.

**Comment by terjeio** [comment]
Is this when connecting with a sender and/or a terminal?

**Comment by vvv1954** [comment]
With Candle and LaserGRBL.

**Comment by vvv1954** [comment]
With terminal (Espressif IDE) as follows
![image](https://user-images.githubusercontent.com/77076378/162631854-74cf4079-8e98-4d35-a9e5-1bc23b9c6174.png)

**Comment by terjeio** [comment]
Try with [compatibility level](https://github.com/grblHAL/core/wiki/Compatibility-level) > 0, or [ioSender](https://github.com/terjeio/ioSender) if on Windows.

**Comment by vvv1954** [comment]
I uploaded your build with "ninja flash" and everything is working (it was uploaded before with Espressif Download Tool). However when I am doing the same with my build it goes to the loop above. 

It seems there is something wrong with my Espressif IDE installation: mainly it reports no errors, but somtimes the errors like "bool not defined" of the warnings like "Member 'flash_size' was not initialized in this constructor" appear.

**Comment by terjeio** [comment]
If you are not modifying code you may try the [Web Builder](http://svn.io-engineering.com:8080/) to generate firmware.
I am closing this issue as I have no idea about what is causing this issue and I have never seen it during development.
