### ISSUE TITLE
SOLVED: Question about I2S and I2C

### ISSUE THREAD

**Issue by ennio64** [grblHAL/ESP32#27]
Hallo
I'm trying to create map file for a MKS Tinybee board.
I assigned GPIO pin at X_lim, Y_lim, Z_lim, A_lim, B_lim, Probe, Feed Hold and Cycle Start and work well.
I use the I2S pin for the stepper motor (XYZAB) and all work well.
I use the I2S pin also for the other signals (flood, mist ,spindle enable and spindle direction) but not work.
I think, but I'm not sure, that I2S is dedicated only to stepper.
Now I will try to connect this signals with I2C IOEXPAND (I order the adapter), and I would like to change the default I2C pins (GPIO 22 (SCL) and GPIO 21 (SDA)) with GPIO 4 (SCL) and GPIO 0 (SDA), it's possible?
Every answer is appreciated. Thank's

**Comment by terjeio** [comment]
> I use the I2S pin also for the other signals (flood, mist ,spindle enable and spindle direction) but not work.

Did you change _driver.c_ for that? Try `DIGITAL_OUT`/`DIGITAL_IN` instead of `gpio_set_level`/`gpio_get_level` for those pins.

> Now I will try to connect this signals with I2C IOEXPAND (I order the adapter), and I would like to change the default I2C pins (GPIO 22 (SCL) and GPIO 21 (SDA)) with GPIO 4 (SCL) and GPIO 0 (SDA), it's possible?

You can try? Here is how it is configured in a board map:
```
// Define I2C port/pins
#define I2C_PORT                I2C_NUM_1
#define I2C_SDA                 GPIO_NUM_21
#define I2C_SCL                 GPIO_NUM_22
#define I2C_CLOCK               100000
```

**Comment by ennio64** [comment]
[mks_tinybee_1_0_map.zip](https://github.com/grblHAL/ESP32/files/9167930/mks_tinybee_1_0_map.zip)
SOLVED
I change driver.c and work.
Thank's Terje Io

**Comment by SphaeroX** [comment]
i got a question, not related  to the ticket. how can i single control these pins for another project...
