### ISSUE TITLE
No WCO, can't zero DRO - Bug report

### ISSUE THREAD

**Issue by Henrikastro** [grblHAL/ESP32#41]
I think some new update brought a new bug to this GrblHAL. I can't use G10 L20 to zero the WCS in IoSender or anywhere else, at first I tought it was something I modified in the code that was causing this but I cloned a new version to test it and it's still happening. Also, there is no WCO on every 10 status reports or when using G10L20.

**Comment by terjeio** [comment]
`$10`=?
Work coordinate offset reporting is turned on by a `$10` flag - reset default is on, has it been turned off?
```
$$=10
$10: Status report options as bitfield:
    0 - Position in machine coordinate (1)
    1 - Buffer state (2)
    2 - Line numbers (4)
    3 - Feed & speed (8)
    4 - Pin state (16)
    5 - Work coordinate offset (32)
    6 - Overrides (64)
    7 - Probe coordinates (128)
    8 - Buffer sync on WCO change (256)
    9 - Parser state (512)
    10 - Alarm substatus (1024)
    11 - Run substatus (2048)
```
In ioSender:

![image](https://user-images.githubusercontent.com/20260062/186361807-b7b72fa7-b036-4f57-88e2-6db4580bfa8c.png)
