### ISSUE TITLE
GRBL crashing when I go to zero the axes

### ISSUE THREAD

**Issue by 7cnc** [grblHAL/ESP32#44]
Use TinyBee v1.0 (ESP32) board and it's crashing. After doing HOME and doing some movements when I go to Zero the XYZ axes, Grblhal crashes. After that I need to close ioSender and keep the board. I couldn't identify if the error is an IOSender or GRBLHAL problem.

**Comment by terjeio** [comment]
Which firmware version and options? From ioSender _Help -> About_ you can copy the information to the clipboard and then from there into a comment. 
You may also try to run the code with the _Console_ open and _Verbose_ checked, messages related to the crash may show up there.
