### ISSUE TITLE
Setting Wifi password that contains "!"?

### ISSUE THREAD

**Issue by errolt** [grblHAL/ESP32#55]
How do I set the station wifi password when the password contains an exclamation mark?
I can set the password via $75, but the moment I enter the ! character, the serial terminal becomes unresponsive and I have to do a hard reset.

Even just a plain "!" on a new line will crash the board.

**Comment by terjeio** [comment]
Try with `$39=0` - this disables printable real-time command characters being processed when part of $ commands.

**Comment by errolt** [comment]
> Try with `$39=0` - this disables printable real-time command characters being processed when part of $ commands.

Thanks! That worked.
