### ISSUE TITLE
Compile with vscode win 10.

### ISSUE THREAD

**Issue by RDS356** [grblHAL/ESP32#65]
Hi. Is there a tutorial to compile using vscode on windows ? I didn't find anything that can help me.

**Comment by terjeio** [comment]
[A search returns plenty of hits](https://duckduckgo.com/?t=ffab&q=esp32+vscode&ia=web).

However, if you do not need to change code and/or a map file then using the [Web Builder](http://svn.io-engineering.com:8080/) is the easiest way to create a binary.

**Comment by RDS356** [comment]
I have my own board, actually I'm using fluidnc, but I could see that grblhal is much more robust. I'm not advanced user regarding low level programing. Unfortunately I will leave grblhall by  this. Sucees for all.
Below a picture of the my board.

![IMG_1410](https://user-images.githubusercontent.com/25726497/228982510-0776d271-fbc9-4e98-addd-83624afe34cd.JPG)
