### ISSUE TITLE
Enable Hard Limits for A-axis with BlackBox X32

### ISSUE THREAD

**Issue by petervanderwalt** [grblHAL/ESP32#67]
Hi!

https://github.com/grblHAL/ESP32/blob/57e54a19dd4613415703aff5b51cad371120bd7f/main/BlackBoxX32_map.h#L56-L57

We have this to re-use the Probe input as an endstop for Auto Squaring

Can we please also have it so it uses the Probe input for 4th axes homing? 

Sadly that means 4th axes users are going to lose probing, so https://github.com/grblHAL/ESP32/issues/64#issuecomment-1490190062 would still be really cool to have so we can get Probing back for 4th axes and auto squaring users

**Comment by terjeio** [comment]
See this [comment](https://github.com/grblHAL/ESP32/issues/64#issuecomment-1492277190).
