### ISSUE TITLE
no define function stream_rx_backup

### ISSUE THREAD

**Issue by cjj0144** [grblHAL/ESP32#7]
esp32-hal-uart.c line 106

**Comment by terjeio** [comment]
Fix committed. Please reopen if still a problem as I have not tested it (test bench is overcrowded).

**Comment by cjj0144** [comment]
> Fix committed. Please reopen if still a problem as I have not tested it (test bench is overcrowded).

haha, much thanks .  i think i will help you complete it. if you need.
