### ISSUE TITLE
Q: Flashing XPro V5

### ISSUE THREAD

**Issue by dwkdnvr** [grblHAL/ESP32#85]
I have an XPro V5 running the original grblESP32 firmware that I want to upgrade to grblHAL. The instructions for upgrading the XPro to FluidNC are a bit complicated and suggest erasing the flash and SD before re-flashing. Do I need to do this with grblHAL as well, or can I just hit the programming button and flash the firmware?

**Comment by terjeio** [comment]
Can't see why just hitting the programming button would not work. So IMO try it.
