### ISSUE TITLE
Failed to initialize SD card

### ISSUE THREAD

**Issue by C4rdsh4rk** [grblHAL/ESP32#88]
Since the new update, the SD Card isn't initialized anymore.
Board: MKS DLC32
I've tried to format the SD again, but it doesn't help.

**Comment by terjeio** [comment]
Reverted now, changed due to another user reporting the same issue _and_ the schematic using ambiguous labels.

**Comment by C4rdsh4rk** [comment]
I have flashed the update, but still can't mount the sd with $FM. The Webui also doesn't show the card in the files tab

**Comment by C4rdsh4rk** [comment]
Fixed with the newest commit. Thanks
