### ISSUE TITLE
typo in vscode ini files

### ISSUE THREAD

**Issue by shaise** [grblHAL/ESP32#89]
Hi @terjeio ,

Not sure if it is on purpose, but I think there is an extra '@' in the vscode ini files:
![image](https://github.com/grblHAL/ESP32/assets/5813568/2c7d888f-cff2-4541-b01c-2ade2d869723)

shai

**Comment by terjeio** [comment]
A copy/paste error, sorry about that - fixed now.

**Comment by shaise** [comment]
thanks!

**Comment by shaise** [comment]
I see the web build of CNC3040 seems to work now, so thanks for that as well!
