### ISSUE TITLE
Web Builder  - auto square

### ISSUE THREAD

**Issue by boboxx** [grblHAL/ESP32#93]
I'm unable to enable auto square on a ESP32 Tinybee 3 axis. 

Bottom error: AUTO SQUARE: available 0, required 1.

Looks like a bug

**Comment by terjeio** [comment]
Fixed now. This board is a bit problematic since limit inputs for auto-squared axes blocks the use of the SD card - I have not figured out how to declare that in the Web Builder board definition and add handle the needed logic to keep the UI up to date.

**Comment by boboxx** [comment]
I'm not sure I understand. You can use MD_DET for a spare axis squaring.

  y:
      limit pin: gpio.32      
      limit pin: gpio.35 (MT_DET)

**Comment by boboxx** [comment]
I'm not sure I understand. You can use MD_DET for a spare axis squaring. This is how i had it configured in FluidNC and was working fine.

y:
motor 0:
limit pin: gpio.32
step_pin: I2SO.4:low
direction_pin: I2SO.5
disable_pin: I2SO.3
motor 1:
limit pin: gpio.35 (MT_DET)
step_pin: I2SO.10
direction_pin: I2SO.11
disable_pin: I2SO.9  

Sd card is on cs_pin: gpio.5

**Comment by terjeio** [comment]
> You can use MD_DET for a spare axis squaring.

Sure, but the map file was originally submitted by a user so perhaps I have to make an alterative to it. Will decide tomorrow.
