### ISSUE TITLE
How to invert motor fault pin?

### ISSUE THREAD

**Issue by RealTadango** [grblHAL/ESP32#98]
I am trying to build for my custom CNC and i have closed loop steppers with a fault output that pulls to ground when an error occurs. I want to use the motor fault input for this but this input is active high. There is a pullup in place so this fault is triggered by default unless the pin is pulled low... but my motors work in the opposite way. How can i reverse the fault trigger? So pin high in normal state and low in faulted state?

**Comment by terjeio** [comment]
It is controlled by a bit in $14. Send `$$=14` for info.

**Comment by RealTadango** [comment]
Ah perfect. Btw, where should i have found this in the Wiki?
